[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_protocol = wiring
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[env:micro]
platform = atmelavr
board = micro
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library